import arcade

from typing import List

SCREEN_WIDTH: int = 1024
SCREEN_HEIGHT: int = 768
SCREEN_TITLE: str = 'Knuckle Bones'
BACKGROUND_COLOR: arcade.Color = arcade.color.JET

DICE_SCALE: float = 0.7
DICE_DIMENSIONS: float = 100 * DICE_SCALE

TILE_PERCENT_OVERSIZE: float = 1.25
TILE_DIMENSIONS: int = int(DICE_DIMENSIONS * TILE_PERCENT_OVERSIZE)

VERTICAL_MARGIN_PERCENT: float = 0.07
HORIZONTAL_MARGIN_PERCENT: float = 0.07
TILE_X_SPACING: float = TILE_DIMENSIONS + TILE_DIMENSIONS * HORIZONTAL_MARGIN_PERCENT
TILE_Y_SPACING: float = TILE_DIMENSIONS + TILE_DIMENSIONS * VERTICAL_MARGIN_PERCENT
TILE_COLOR: arcade.Color = arcade.color.DARK_OLIVE_GREEN
TILE_COLOR_LIST: List[arcade.Color] = [arcade.color.DARK_OLIVE_GREEN, arcade.color.DARK_SEA_GREEN, arcade.color.AERO_BLUE]

BOARD_X_START: float = SCREEN_WIDTH / 2 - TILE_X_SPACING

TOP_BOARD_Y: float = VERTICAL_MARGIN_PERCENT * TILE_DIMENSIONS + SCREEN_HEIGHT - TILE_DIMENSIONS * 3
BOTTOM_BOARD_Y: float = VERTICAL_MARGIN_PERCENT * TILE_DIMENSIONS + TILE_DIMENSIONS * 3

DICE_TRAY_WIDTH: int = 250
DICE_TRAY_HEIGHT: int = 150

TOP_TRAY_X: int  = SCREEN_WIDTH - 175
TOP_TRAY_Y: int = SCREEN_HEIGHT - TILE_DIMENSIONS - TILE_DIMENSIONS

BOTTOM_TRAY_X: int = 175
BOTTOM_TRAY_Y: int = TILE_DIMENSIONS + TILE_DIMENSIONS

PLAYER_ONE: str = 'Player 1'
PLAYER_TWO: str = 'Player 2'

ATTACKED_DICE_COLOR = arcade.color.CARMINE_PINK
THREE_X_MOD_COLOR = arcade.color.BALL_BLUE
TWO_X_MOD_COLOR = arcade.color.AFRICAN_VIOLET
